# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Think',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('think', models.TextField(max_length=1000, verbose_name='想法')),
                ('nation', models.CharField(blank=True, max_length=20, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=20, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('created', models.DateTimeField(verbose_name='创建时间')),
                ('weixin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.weixinUsers')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
