# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weixinUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50, verbose_name='openid')),
                ('unionid', models.CharField(default='', max_length=50, verbose_name='uuid')),
                ('session_key', models.CharField(default='', max_length=50)),
                ('sid', models.UUIDField(default=uuid.uuid1)),
                ('is_del', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-pk'],
                'get_latest_by': 'pk',
            },
        ),
    ]
